USE HR;  
GO  

ALTER TABLE COUNTRIES  
NOCHECK CONSTRAINT FK_REGION_ID;  
GO

ALTER TABLE LOCATIONS  
NOCHECK CONSTRAINT FK_COUNTRY_ID;  
GO

ALTER TABLE DEPARTMENTS  
NOCHECK CONSTRAINT FK_LOCATION_ID_DEPT;  
GO

ALTER TABLE DEPARTMENTS  
NOCHECK CONSTRAINT FK_DEPT_MAN_ID;  
GO

ALTER TABLE EMPLOYEES  
NOCHECK CONSTRAINT FK_JOB_ID;  
GO

ALTER TABLE EMPLOYEES  
NOCHECK CONSTRAINT FK_MANAGER;  
GO

ALTER TABLE EMPLOYEES  
NOCHECK CONSTRAINT FK_DEPT_ID;  
GO

ALTER TABLE JOB_HISTORY  
NOCHECK CONSTRAINT FK_EMP_ID;  
GO

ALTER TABLE JOB_HISTORY  
NOCHECK CONSTRAINT FK_JOBS;  
GO

ALTER TABLE JOB_HISTORY  
NOCHECK CONSTRAINT FK_DEPT_ID_JH;  
GO