USE HR;  
GO  

ALTER TABLE COUNTRIES  
CHECK CONSTRAINT FK_REGION_ID;  
GO

ALTER TABLE LOCATIONS  
CHECK CONSTRAINT FK_COUNTRY_ID;  
GO

ALTER TABLE DEPARTMENTS  
CHECK CONSTRAINT FK_LOCATION_ID_DEPT;  
GO

ALTER TABLE DEPARTMENTS  
CHECK CONSTRAINT FK_DEPT_MAN_ID;  
GO

ALTER TABLE EMPLOYEES  
CHECK CONSTRAINT FK_JOB_ID;  
GO

ALTER TABLE EMPLOYEES  
CHECK CONSTRAINT FK_MANAGER;  
GO

ALTER TABLE EMPLOYEES  
CHECK CONSTRAINT FK_DEPT_ID;  
GO

ALTER TABLE JOB_HISTORY  
CHECK CONSTRAINT FK_EMP_ID;  
GO

ALTER TABLE JOB_HISTORY  
CHECK CONSTRAINT FK_JOBS;  
GO

ALTER TABLE JOB_HISTORY  
CHECK CONSTRAINT FK_DEPT_ID_JH;  
GO