--CREATE DATABASE HR;
--USE HR;

CREATE TABLE REGIONS(
   REGION_ID   INTEGER  NOT NULL PRIMARY KEY 
  ,REGION_NAME VARCHAR(22) NOT NULL
);

CREATE TABLE COUNTRIES(
   COUNTRY_ID   VARCHAR(2) NOT NULL PRIMARY KEY
  ,COUNTRY_NAME VARCHAR(24) NOT NULL
  ,REGION_ID    INTEGER  NOT NULL --fk regions
  CONSTRAINT FK_REGION_ID FOREIGN KEY (REGION_ID)
  REFERENCES REGIONS (REGION_ID)
);

CREATE TABLE LOCATIONS(
   LOCATION_ID    VARCHAR(4) NOT NULL PRIMARY KEY
  ,STREET_ADDRESS VARCHAR(40) NOT NULL
  ,POSTAL_CODE    VARCHAR(10)
  ,CITY           VARCHAR(19) NOT NULL
  ,STATE_PROVINCE VARCHAR(17)
  ,COUNTRY_ID     VARCHAR(2) NOT NULL --fk countries
  CONSTRAINT FK_COUNTRY_ID FOREIGN KEY (COUNTRY_ID)
  REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE JOBS(
   JOB_ID     VARCHAR(10) NOT NULL PRIMARY KEY
  ,JOB_TITLE  VARCHAR(31) NOT NULL
  ,MIN_SALARY VARCHAR(5) NOT NULL
  ,MAX_SALARY VARCHAR(5) NOT NULL
);

CREATE TABLE DEPARTMENTS(
   DEPARTMENT_ID   INTEGER  NOT NULL PRIMARY KEY 
  ,DEPARTMENT_NAME VARCHAR(20) NOT NULL
  ,MANAGER_ID      INTEGER  --fk employees
  ,LOCATION_ID     VARCHAR(4)  NOT NULL --fk locations
  CONSTRAINT FK_LOCATION_ID_DEPT FOREIGN KEY (LOCATION_ID)
  REFERENCES LOCATIONS (LOCATION_ID)
);

CREATE TABLE EMPLOYEES(
   "EMPLOYEE_ID"    INTEGER  NOT NULL PRIMARY KEY 
  ,"FIRST_NAME"     VARCHAR(20) NOT NULL
  ,"LAST_NAME"      VARCHAR(20) NOT NULL
  ,EMAIL            VARCHAR(15) NOT NULL
  ,"PHONE_NUMBER"   VARCHAR(20) NOT NULL
  ,"HIRE_DATE"      DATE  NOT NULL
  ,"JOB_ID"         VARCHAR(10) NOT NULL --fk jobs
  ,SALARY           INTEGER  NOT NULL
  ,"COMMISSION_PCT" NUMERIC(4,2)
  ,"MANAGER_ID"     INTEGER --fk employees
  ,"DEPARTMENT_ID"  INTEGER -- fk departments
  CONSTRAINT FK_JOB_ID FOREIGN KEY (JOB_ID)
  REFERENCES JOBS (JOB_ID),
  CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID),
  CONSTRAINT FK_DEPT_ID FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

CREATE TABLE JOB_HISTORY(
   EMPLOYEE_ID   INTEGER  NOT NULL --fk employees
  ,START_DATE    DATE  NOT NULL
  ,END_DATE      DATE  NOT NULL
  ,JOB_ID        VARCHAR(10) NOT NULL --fk jobs
  ,DEPARTMENT_ID INTEGER  NOT NULL --fk departments 
  CONSTRAINT FK_EMP_ID FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID),
  CONSTRAINT FK_JOBS FOREIGN KEY(JOB_ID)
  REFERENCES JOBS (JOB_ID),
  CONSTRAINT FK_DEPT_ID_JH FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

ALTER TABLE DEPARTMENTS 
	ADD CONSTRAINT FK_DEPT_MAN_ID FOREIGN KEY (MANAGER_ID)
	REFERENCES EMPLOYEES (EMPLOYEE_ID);