INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES (1,'Europe');
INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES (2,'Americas');
INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES (3,'Asia');
INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES (4,'Middle East and Africa');
